require_relative "./Piece.rb"
require_relative "./NullPiece.rb"
require_relative "./Rook.rb"
# require_relative "./slidable.rb"
# require_relative "./Steppable.rb"
require_relative "./bishop.rb"
require_relative "./Queen.rb"
require_relative "./King.rb"
require_relative "./Pawn.rb"
require_relative "./Cursor.rb"
require_relative "./Knight.rb"